import type { Robot, Site } from './index.js';

export const sites = [
  {
    id: 'berlin-fulfillment',
    name: 'Berlin Fulfillment Center',
    timezone: 'Europe/Berlin',
    features: [
      {
        id: 'bf-inbound',
        label: 'Inbound',
        type: 'zone',
        x: 4,
        y: 8,
        width: 24,
        height: 36,
      },
      {
        id: 'bf-storage',
        label: 'Storage',
        type: 'zone',
        x: 34,
        y: 8,
        width: 40,
        height: 62,
      },
      {
        id: 'bf-packing',
        label: 'Packing',
        type: 'zone',
        x: 78,
        y: 8,
        width: 18,
        height: 62,
      },
      {
        id: 'bf-block',
        label: 'Safety barrier',
        type: 'obstacle',
        x: 24,
        y: 76,
        width: 48,
        height: 8,
      },
      {
        id: 'bf-charge',
        label: 'Charging',
        type: 'charger',
        x: 78,
        y: 78,
        width: 18,
        height: 14,
      },
    ],
  },
  {
    id: 'hamburg-hub',
    name: 'Hamburg Distribution Hub',
    timezone: 'Europe/Berlin',
    features: [
      {
        id: 'hh-dock',
        label: 'Dock',
        type: 'zone',
        x: 5,
        y: 8,
        width: 20,
        height: 80,
      },
      {
        id: 'hh-sort',
        label: 'Sorting',
        type: 'zone',
        x: 31,
        y: 8,
        width: 38,
        height: 46,
      },
      {
        id: 'hh-dispatch',
        label: 'Dispatch',
        type: 'zone',
        x: 75,
        y: 8,
        width: 20,
        height: 46,
      },
      {
        id: 'hh-block',
        label: 'Conveyor',
        type: 'obstacle',
        x: 31,
        y: 62,
        width: 64,
        height: 10,
      },
      {
        id: 'hh-charge',
        label: 'Charging',
        type: 'charger',
        x: 75,
        y: 78,
        width: 20,
        height: 12,
      },
    ],
  },
] as const satisfies readonly Site[];

export const robots = [
  {
    id: 'bf-01',
    name: 'Ada',
    siteId: 'berlin-fulfillment',
    model: 'OLV-Courier Mk2',
  },
  {
    id: 'bf-02',
    name: 'Babbage',
    siteId: 'berlin-fulfillment',
    model: 'OLV-Courier Mk2',
  },
  {
    id: 'bf-03',
    name: 'Curie',
    siteId: 'berlin-fulfillment',
    model: 'OLV-Lifter Mk1',
  },
  {
    id: 'bf-04',
    name: 'Darwin',
    siteId: 'berlin-fulfillment',
    model: 'OLV-Courier Mk2',
  },
  {
    id: 'bf-05',
    name: 'Euler',
    siteId: 'berlin-fulfillment',
    model: 'OLV-Lifter Mk1',
  },
  {
    id: 'bf-06',
    name: 'Faraday',
    siteId: 'berlin-fulfillment',
    model: 'OLV-Courier Mk2',
  },
  {
    id: 'bf-07',
    name: 'Grace',
    siteId: 'berlin-fulfillment',
    model: 'OLV-Courier Mk2',
  },
  {
    id: 'bf-08',
    name: 'Hopper',
    siteId: 'berlin-fulfillment',
    model: 'OLV-Lifter Mk1',
  },
  {
    id: 'hh-01',
    name: 'Ishiguro',
    siteId: 'hamburg-hub',
    model: 'OLV-Courier Mk2',
  },
  {
    id: 'hh-02',
    name: 'Jemison',
    siteId: 'hamburg-hub',
    model: 'OLV-Lifter Mk1',
  },
  {
    id: 'hh-03',
    name: 'Kepler',
    siteId: 'hamburg-hub',
    model: 'OLV-Courier Mk2',
  },
  {
    id: 'hh-04',
    name: 'Lovelace',
    siteId: 'hamburg-hub',
    model: 'OLV-Courier Mk2',
  },
  {
    id: 'hh-05',
    name: 'Minsky',
    siteId: 'hamburg-hub',
    model: 'OLV-Lifter Mk1',
  },
  {
    id: 'hh-06',
    name: 'Noether',
    siteId: 'hamburg-hub',
    model: 'OLV-Courier Mk2',
  },
  { id: 'hh-07', name: 'Ohm', siteId: 'hamburg-hub', model: 'OLV-Courier Mk2' },
  {
    id: 'hh-08',
    name: 'Pascal',
    siteId: 'hamburg-hub',
    model: 'OLV-Lifter Mk1',
  },
] as const satisfies readonly Robot[];
